spring:
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: 1747303432@qq.com
    password: agtbhalkppnrdcec
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: utf-8
    jndi-name:
    test-connection:
